# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1688GHYOUQC-ZXy9MH9eEmBUcOCpLDt-d
"""

#monotonic[1,2,3,4]
mylist=[1,2,3,4]
monotonic=0
x=len(mylist)-1
for i in range(1,len(mylist)):
  if(mylist[i-1]<mylist[i]):
    monotonic+=1
  elif(mylist[i-1]>mylist[i]):
    monotonic+=2
  else:
    print("Non monotonic")
    break
if(monotonic==x):
  print("Monotonic increaasing")
elif(monotonic==2*x):
  print("monotonic de")

mylist=[1,2,3,5,5]
increase=0
decrease=0
x=len(mylist)-1
for i in range(1,len(mylist)):
  if (mylist[i]>mylist[i-1]):
    decrease+=1
  elif(mylist[i]<mylist[i-1]):
    increase+=2
if(decrease==x):
    print("monotonic")
elif(increase==2*x):
    print("Monotonic")
else:
    print("non monotonic")

num=1000
count=0
sum=0
temp=num
a=num

while(num>0):
    num=num//10
    count+=1
while(temp>0):
    rem=temp%10
    sum=sum+(rem**count)
    temp=temp//10
    count-=1
if (a==sum):
  print(a)
else:
  print("not")



num=81
temp=num
sum=0
while(num>0):
  rem=num%10
  sum=sum+rem
  num=num//10
if(temp%sum==0):
  print("Harshad number")
else:
  print("not")

#zip and enumerate for learning assingment